language: node_js

node_js:
- 4.2.2

before_script: echo "Build the project : )"

script: echo "Tested : )"

deploy:
  acl              : public_read
  bucket           : hackathon.transloadit.com
  cache_control    : no-cache
  local-dir        : build
  provider         : s3
  skip_cleanup     : true
  upload-dir       : transloadit-js-client/$TRAVIS_BRANCH
  access_key_id    : AKIAI45MV2S7O67ZPLXA
  secret_access_key:
    secure: k+T/4s49gdbNftD8HSyfUU2UoF1His/11Fu5YcZjUTfjtroqozqf7JV7nW7hB86wkHzXamS/0SlsEhC/P7bgJ3jnrzQfoSFZDr3lJSMBsiVqwzTnyltqrerWqZQNYvcdu9sUOH6UCOpVjKZYB71k84gmgeSmPlyyH0ukziYex/bhs3qyaaix8GkyP58C9Z2PssIew6s/mVNYveidgWdMe3OxMVvfwYHlZ8euJ8QDvGWlKj/9Hh3W/BW6BcTmnzZONf8c4me0C0gZ6HbLtYCfkUB1r1mvKRiLviOOnFHzmNhM/7a+srgaPgY8CF0dQ7dO1wN5k8ClrF33jytFWz2R4ZZgzKzWxYgZ7tisqTjhBlbcKBDJNw05Y6bu7Fiyyw7HY1/mibK+Fu7Rfvt6ZBjDVJtmXiLSMT2vD1rMLUa+MyDCIyG2iNARThbj0aQbrkVjviYYXqG/2vQjKWlqJ9Sus0v0Y/jqkVwpviohGd2F2iPEqBexLYgBaxU/LgTBTYAKJ0SzKosRAW4dYxm6dnWABV1v7oxIUJAKvt51haNGqTO4a87UzAHa4ND2nZBYLWdKoGCKWmV3DBtI/ha2Re6gO2HoK95S3ZRV8hfT3Nzt2wONNtiObuuv7U+osh62wvX5Rj0XHb/sV3vopjJpanmm+zYWtI/+k/+453XNMOIXmBA=
  on:
    repo: transloadit/transloadit-js-client
    all_branches: true
